platform :ios, '13.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

$EnableCoreMLDelegate = true

target 'MuseumBingo' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath]
  )

  pod 'TensorFlowLiteC', '~> 2.13.0'
  pod 'TensorFlowLiteC/CoreML', '~> 2.13.0'
  pod 'react-native-maps', path: '../node_modules/react-native-maps'

  # AR confetti bridge module (custom native source in ios/MuseumBingo).
  # ARKit/SceneKit are iOS system frameworks and don't need CocoaPods packages.
  pod 'React-Core'
end
