import { ArtworkMetadata } from "./types";

export const MOMA_ARTWORKS: ArtworkMetadata[] = [
  {
    id: "moma_001",
    museumId: "moma_nyc",
    title: "The Starry Night",
    artist: "Vincent van Gogh",
    description: "Post-impressionist landscape with swirling night sky.",
    imageS3Key: "museums/moma_nyc/raw/moma_001.jpg",
    resizedS3Key: "museums/moma_nyc/resized/moma_001.jpg",
    locationX: 10.0,
    locationY: 15.0,
    bingoTileId: "0_0",
    embedding: new Float32Array(512),
  },
  {
    id: "moma_002",
    museumId: "moma_nyc",
    title: "The Persistence of Memory",
    artist: "Salvador Dali",
    description: "Surrealist melting clocks in a barren landscape.",
    imageS3Key: "museums/moma_nyc/raw/moma_002.jpg",
    resizedS3Key: "museums/moma_nyc/resized/moma_002.jpg",
    locationX: 25.3,
    locationY: 40.7,
    bingoTileId: "0_1",
    embedding: new Float32Array(512),
  },
  {
    id: "moma_003",
    museumId: "moma_nyc",
    title: "Campbell's Soup Cans",
    artist: "Andy Warhol",
    description: "32 canvases each featuring a different soup flavor.",
    imageS3Key: "museums/moma_nyc/raw/moma_003.jpg",
    resizedS3Key: "museums/moma_nyc/resized/moma_003.jpg",
    locationX: 55.0,
    locationY: 60.0,
    bingoTileId: "0_2",
    embedding: new Float32Array(512),
  },
  {
    id: "moma_004",
    museumId: "moma_nyc",
    title: "One: Number 31, 1950",
    artist: "Jackson Pollock",
    description: "Abstract expressionist drip painting.",
    imageS3Key: "museums/moma_nyc/raw/moma_004.jpg",
    resizedS3Key: "museums/moma_nyc/resized/moma_004.jpg",
    locationX: 80.0,
    locationY: 25.5,
    bingoTileId: "1_0",
    embedding: new Float32Array(512),
  },
];

export const GUGGENHEIM_ARTWORKS: ArtworkMetadata[] = [
  {
    id: "gug_001",
    museumId: "guggenheim_nyc",
    title: "Composition 8",
    artist: "Wassily Kandinsky",
    description: "Geometric abstraction with circles, lines, and curves.",
    imageS3Key: "museums/guggenheim_nyc/raw/gug_001.jpg",
    resizedS3Key: "museums/guggenheim_nyc/resized/gug_001.jpg",
    locationX: 30.0,
    locationY: 45.0,
    bingoTileId: "0_0",
    embedding: new Float32Array(512),
  },
  {
    id: "gug_002",
    museumId: "guggenheim_nyc",
    title: "The Guggenheim Ramp",
    artist: "Robert Irwin",
    description: "Site-specific installation along the spiral ramp.",
    imageS3Key: "museums/guggenheim_nyc/raw/gug_002.jpg",
    resizedS3Key: "museums/guggenheim_nyc/resized/gug_002.jpg",
    locationX: 55.0,
    locationY: 55.0,
    bingoTileId: "0_1",
    embedding: new Float32Array(512),
  },
];
