import { ArtworkMetadata } from "./types";

export const MET_ARTWORKS: ArtworkMetadata[] = [
  {
    id: "met_001",
    museumId: "met_nyc",
    title: "Whistler's Mother",
    artist: "James McNeill Whistler",
    description: "Iconic painting of an elderly woman seated in profile, dressed in black.",
    imageS3Key: "museums/met_nyc/raw/met_001.jpg",
    resizedS3Key: "museums/met_nyc/resized/met_001.jpg",
    locationX: 24.5,
    locationY: 12.3,
    bingoTileId: "0_0",
    embedding: new Float32Array(512),
  },
  {
    id: "met_002",
    museumId: "met_nyc",
    title: "The Thinker",
    artist: "Auguste Rodin",
    description: "Bronze sculpture of a nude male figure sitting on a rock, deep in thought.",
    imageS3Key: "museums/met_nyc/raw/met_002.jpg",
    resizedS3Key: "museums/met_nyc/resized/met_002.jpg",
    locationX: 45.2,
    locationY: 20.1,
    bingoTileId: "0_1",
    embedding: new Float32Array(512),
  },
  {
    id: "met_003",
    museumId: "met_nyc",
    title: "Self-Portrait with a Straw Hat",
    artist: "Vincent van Gogh",
    description: "The artist looks at the viewer with intense, suspicious eyes.",
    imageS3Key: "museums/met_nyc/raw/met_003.jpg",
    resizedS3Key: "museums/met_nyc/resized/met_003.jpg",
    locationX: 60.0,
    locationY: 55.0,
    bingoTileId: "0_2",
    embedding: new Float32Array(512),
  },
  {
    id: "met_004",
    museumId: "met_nyc",
    title: "Washington Crossing the Delaware",
    artist: "Emanuel Leutze",
    description: "Dramatic depiction of George Washington crossing the Delaware River.",
    imageS3Key: "museums/met_nyc/raw/met_004.jpg",
    resizedS3Key: "museums/met_nyc/resized/met_004.jpg",
    locationX: 15.8,
    locationY: 40.2,
    bingoTileId: "1_0",
    embedding: new Float32Array(512),
  },
  {
    id: "met_005",
    museumId: "met_nyc",
    title: "The Unicorn in Captivity",
    artist: "Unknown (South Netherlandish)",
    description: "Medieval tapestry with gold leaf details, showing a unicorn in a garden.",
    imageS3Key: "museums/met_nyc/raw/met_005.jpg",
    resizedS3Key: "museums/met_nyc/resized/met_005.jpg",
    locationX: 70.3,
    locationY: 30.7,
    bingoTileId: "1_1",
    embedding: new Float32Array(512),
  },
  {
    id: "met_006",
    museumId: "met_nyc",
    title: "Still Life with Apples and a Pot of Primroses",
    artist: "Paul Cezanne",
    description: "Tabletop arrangement of apples and flowers.",
    imageS3Key: "museums/met_nyc/raw/met_006.jpg",
    resizedS3Key: "museums/met_nyc/resized/met_006.jpg",
    locationX: 33.1,
    locationY: 72.5,
    bingoTileId: "1_2",
    embedding: new Float32Array(512),
  },
  {
    id: "met_007",
    museumId: "met_nyc",
    title: "Portrait of a King (Henry VIII)",
    artist: "Hans Holbein the Younger",
    description: "Full-length portrait of Henry VIII in royal regalia.",
    imageS3Key: "museums/met_nyc/raw/met_007.jpg",
    resizedS3Key: "museums/met_nyc/resized/met_007.jpg",
    locationX: 82.0,
    locationY: 45.0,
    bingoTileId: "2_0",
    embedding: new Float32Array(512),
  },
  {
    id: "met_008",
    museumId: "met_nyc",
    title: "Seashell (The Conch)",
    artist: "John La Farge",
    description: "Watercolor of a large seashell with pearl tones.",
    imageS3Key: "museums/met_nyc/raw/met_008.jpg",
    resizedS3Key: "museums/met_nyc/resized/met_008.jpg",
    locationX: 12.4,
    locationY: 88.9,
    bingoTileId: "2_1",
    embedding: new Float32Array(512),
  },
  {
    id: "met_009",
    museumId: "met_nyc",
    title: "The Death of Sardanapalus",
    artist: "Eugene Delacroix",
    description: "Romantic painting filled with text and chaos.",
    imageS3Key: "museums/met_nyc/raw/met_009.jpg",
    resizedS3Key: "museums/met_nyc/resized/met_009.jpg",
    locationX: 55.5,
    locationY: 10.2,
    bingoTileId: "2_2",
    embedding: new Float32Array(512),
  },
];
